services:
  discordbot:
    build:
      target: development
    volumes:
      - ./apps/discordbot/src:/app/src
    environment:
      - DEBUG=true

  dj-backend:
    build:
      target: development
    volumes:
      - ./apps/dj-backend/src:/app/src
    environment:
      - DEBUG=true

  react-frontend:
    build:
      context: ./apps/react-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/react-frontend/app:/app/app
      - ./apps/react-frontend/public:/app/public
    ports:
      - "5173:5173"
    command: npm run dev -- --host --force
    environment:
      - DOCKER=true

  nginx:
    volumes:
      - ./apps/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
