# Generated by Django 5.2.12 on 2026-03-30 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                ("discord_id", models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ("username", models.CharField(max_length=64)),
                ("global_name", models.CharField(blank=True, max_length=64, null=True)),
                ("avatar", models.CharField(blank=True, max_length=256, null=True)),
                ("access_token", models.CharField(max_length=256)),
                ("refresh_token", models.CharField(max_length=256)),
                ("token_expires_at", models.DateTimeField()),
                ("scope", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discord", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
