# Generated by Django 5.2.12 on 2026-03-30 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0001_initial"),
        ("youtube", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordGuild",
            fields=[
                ("guild_id", models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GuildQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="queue", to="discord.discordguild"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuildQueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="discord.guildqueue"
                    ),
                ),
                ("video", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="youtube.youtubevideo")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
