# Generated by Django 5.2.12 on 2026-04-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0002_discordguild_guildqueue_guildqueueitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguild",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
