# Generated by Django 5.2.12 on 2026-04-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0003_alter_discordguild_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildqueueitem",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queue_items",
                to="discord.discorduser",
            ),
        ),
    ]
