# Generated by Django 5.2.12 on 2026-04-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0004_alter_guildqueueitem_added_by"),
        ("youtube", "0003_alter_youtubevideo_source_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guildqueueitem",
            name="queue",
        ),
        migrations.RemoveField(
            model_name="guildqueueitem",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="guildqueueitem",
            name="video",
        ),
        migrations.CreateModel(
            name="GuildPlaylist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="playlist", to="discord.discordguild"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuildPlaylistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playlist_items",
                        to="discord.discorduser",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="discord.guildplaylist"
                    ),
                ),
                ("video", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="youtube.youtubevideo")),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="guildplaylist",
            name="current_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discord.guildplaylistitem",
            ),
        ),
        migrations.DeleteModel(
            name="GuildQueue",
        ),
        migrations.DeleteModel(
            name="GuildQueueItem",
        ),
    ]
