# Generated by Django 5.2.12 on 2026-03-25 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                (
                    'playlist_type',
                    models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_playlist_id', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('youtube_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['youtube_id'], name='youtube_you_youtube_903cd3_idx'),
                    models.Index(fields=['creator'], name='youtube_you_creator_1862de_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='YoutubePlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='items', to='youtube.youtubeplaylist'
                    ),
                ),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtubevideo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'video')},
            },
        ),
    ]
