# Generated by Django 5.2.12 on 2026-03-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubeplaylist",
            options={},
        ),
        migrations.RenameField(
            model_name="youtubeplaylist",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterUniqueTogether(
            name="youtubeplaylistitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="youtubeplaylist",
            name="id",
        ),
        migrations.RemoveField(
            model_name="youtubeplaylist",
            name="user",
        ),
        migrations.AddField(
            model_name="youtubeplaylist",
            name="channel_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="youtubeplaylist",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="youtubeplaylist",
            name="owned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="youtube_playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="youtubeplaylist",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubeplaylistitem",
            name="added_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="youtubeplaylist",
            name="youtube_playlist_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="youtubeplaylistitem",
            constraint=models.UniqueConstraint(fields=("playlist", "video"), name="unique_video_per_playlist"),
        ),
    ]
