# Generated by Django 5.2.12 on 2026-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0002_alter_youtubeplaylist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideo",
            name="source_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="youtubevideo",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
